
logging:
    level:
        com.SecureBank.backend: DEBUG

my-variables:
    key: IZeiyJbvnjQdA4tu5yc3hg==

app:
    cors:
        allowed-origins: http://localhost:3000
---

spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:postgresql://db:5432/backend
        username: "postgresUser"
        password: "Yn!U4v5zg(k2yxSt[@Vr"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop # (create, create-drop, validate, update)
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
---


spring:
    config:
        activate:
            on-profile: local

    h2:
        console.enabled: true # http://localhost:8080/h2-console
    datasource:
        url: jdbc:h2:mem:db
        username: sa
        password: sa
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
